# Generated by Django 3.0 on 2020-02-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_annonce_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
