# Generated by Django 3.0 on 2020-02-04 19:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_annonce_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='photo',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
