# Generated by Django 3.0 on 2020-02-15 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0006_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
